language: python


python:
  - 3.7

services:
  - redis

sudo: false

install:
  - pip install -r requirements.txt --upgrade
  - pip freeze
  - pip install coveralls

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cp config_wikidata.py config.py
  - pwd

script:
  - coverage run --omit=/home/travis/virtualenv/* -m pytest

after_success:
  - coveralls


