#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
# Taken from https://gist.github.com/ndarville/3625246

language: python


python:
  - 3.4

services:
  - redis

sudo: false

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - cp config_wikidata.py config.py
  - pwd

script:
  - coverage run --omit=/home/travis/virtualenv/* -m unittest tests

after_success:
  - coveralls


